FROM golang:1.17.2-alpine3.14

RUN apk --update add alpine-sdk

ENV GO111MODULE=on

WORKDIR /go/src
COPY go.mod ./
RUN go mod download
RUN go install github.com/cosmtrek/air@latest

WORKDIR /go/src/github.com/binn
CMD ["/bin/sh"]
