name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test code
        run: go test -v ./binn ./server ./client
